"""
main.py — FastAPI application entry point.

This file:
  1. Creates the FastAPI app object
  2. Attaches CORS middleware (allows the React frontend to call the API)
  3. Registers all routers (books, recommendations)
  4. Creates database tables on startup if they don't exist

To run the server:
  cd backend
  uvicorn app.main:app --reload --port 8000

Then visit:
  http://localhost:8000/docs   ← interactive API explorer (auto-generated by FastAPI)
  http://localhost:8000        ← health check
"""

import os
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv

load_dotenv()

# Import must come after load_dotenv so env vars are available
from app.database import engine, Base
from app.routers import books, recommendations

# Create all SQLite tables from the ORM model definitions (safe — won't overwrite existing data)
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Book Recommender API",
    description=(
        "Semantic book recommendation engine. "
        "Uses sentence-transformers to embed book descriptions and ChromaDB "
        "for fast cosine-similarity vector search."
    ),
    version="1.0.0",
    docs_url="/docs",      # Swagger UI
    redoc_url="/redoc",    # Alternative ReDoc UI
)

# ---------------------------------------------------------------------------
# CORS — Cross-Origin Resource Sharing
# Without this, the browser blocks the React frontend (localhost:5173) from
# calling the API (localhost:8000) because they're on different ports.
# ---------------------------------------------------------------------------
cors_origins = os.getenv("CORS_ORIGINS", "http://localhost:5173").split(",")
app.add_middleware(
    CORSMiddleware,
    allow_origins=cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register routers — each adds its own URL prefix (/books, /recommend)
app.include_router(books.router)
app.include_router(recommendations.router)


@app.get("/", tags=["Health"])
def root():
    """Health-check endpoint — confirm the server is alive."""
    return {
        "status": "running",
        "message": "Book Recommender API is live.",
        "docs": "http://localhost:8000/docs",
        "endpoints": {
            "list_books":     "GET  /books",
            "discover_books": "GET  /books/discover?q=<search term>",
            "vibe_recommend": "POST /recommend/vibe",
        },
    }
